# Generated by Django 5.0.6 on 2025-01-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_manager', '0003_alter_car_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cars_manager.car', verbose_name='Автомобиль'),
        ),
    ]
