# Generated by Django 5.0.6 on 2025-01-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_manager', '0004_alter_comments_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
