# Generated by Django 5.0.6 on 2025-01-05 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_manager', '0005_rename_uploaded_at_car_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='cars_manage_created_fbacfb_idx',
            old_name='cars_manage_created_0e0f02_idx',
        ),
    ]
